[OPENAI]
OPENAI_KEY = "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"

[PINECONE]
PINECONE_API_KEY = "74a47ab7-4afb-48a6-a674-1a1c1e899817"

[LANGSMITH]
LANGSMITH_API_KEY = "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"
LANGCHAIN_PROJECT = "first-deployment"